---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-watsonx-self-managed
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 86425cf1-a763-4d17-9bb9-75276274a5f6
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-ocp-instances.sh"
        post_validation: "tests/scripts/post-validation-destroy-ocp-instances.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
