apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.deployer.prefix }}-status
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ .Values.deployer.prefix }}-status
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
